config/routes.rb
Rails.application.routes.draw do

  root to: 'tags#index'

  devise_for :admins, skip: :all
  devise_scope :admin do
    
    get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
    post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'
    delete 'admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'    
  end

  namespace :admins do
    get '/' => 'tags#index', as: 'top'
    resources :tags
    resources :recipes do
      resources :foodstuffs
      resources :recipephotos
      collection do
        get 'search'
      end
    end
    resources :users
  end

  devise_for :users, skip: :all
  devise_scope :user do
    get 'users/sign_in' => 'users/sessions#new', as: 'new_user_session'
    post 'users/sign_in' => 'users/sessions#create', as: 'user_session'
    delete 'users/sign_out' => 'users/sessions#destroy', as: 'destroy_user_session'
    get 'users/sign_up' => 'users/registrations#new', as: 'new_user_registration'
    post 'users' => 'users/registrations#create', as: 'user_registration'
    get 'users/password/new' => 'users/passwords#new', as: 'new_user_password'
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users do
    member do
      get 'nonreleases'
    end
  end

  resources :tags 

  resources :recipes do
    resources :foodstuffs
    resources :recipephotos
    resources :comments
    member do
      get 'recipe_detail'
      get 'nonreleases'
      patch 'nonrelease'
      patch 'release'
    end
    collection do
      get 'search'
    end
  end

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :foodstuffs, dependent: :destroy
  has_many :recipephotos, dependent: :destroy
  has_many :recipe_tag_relations, dependent: :destroy
  has_many :tags, through: :recipe_tag_relations, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_one_attached :main_image
  enum status:{nonreleased: 0, released: 1}
  validates :title, :details, :process, :main_image, presence: true

  def self.search(search)
    return Recipe.all unless search
    Recipe.where(['title LIKE ?', "%#{search}%"])
    Recipe.where(['process LIKE ?', "%#{search}%"])
    Recipe.where(['details LIKE ?', "%#{search}%"])
  end
end

app/controllers/admins/recipes_controller.rb
class Admins::RecipesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_recipe,  only: [:show, :edit, :update]
  before_action :set_recipe_children,  only: [:show, :edit]
  def index
    @recipes = Recipe.all
  end

  def show
    @comments = @recipe.comments
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to admins_recipe_path(@recipe)
    else
      render :edit
    end
  end

  def search
    @recipes = Recipe.search(params[:search]).order("created_at DESC")
  end
  
  private
  def recipe_params
    params.require(:recipe).permit(:title, :process, :details, :main_image, tag_ids: [])
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def set_recipe_children
    @foodstuff = Foodstuff.new
    @foodstuffs = @recipe.foodstuffs
    @recipephoto = Recipephoto.new
    @recipephotos = @recipe.recipephotos
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_recipe,           only: [:recipe_detail, :edit, :show, :update, :destroy, :release, :nonrelease]
  before_action :set_recipe_children,  only: [:recipe_detail, :show, :edit]

  def index
    @recipe = Recipe.includes(:user).order("created_at DESC")
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.valid?
      @recipe.save
      redirect_to recipe_detail_recipe_path(@recipe.id)
    else
      render new_recipe_path(@recipe.id)
    end
  end

  def recipe_detail
  end

  def show
    @comment = Comment.new
    @comments = @recipe.comments
  end

  def edit
    if @recipe.user != current_user
      render :edit
    end
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe.id), method: :get
    else
      render :edit
    end
  end

  def destroy
    @recipe.destroy
    redirect_to root_path
  end

  def release
    @recipe.released! unless @recipe.released?
    redirect_to recipe_path(@recipe)
  end

  def nonrelease
    @recipe.nonreleased! unless @recipe.nonreleased?
    redirect_to recipe_path(@recipe)
  end

  def search
    @recipes = Recipe.search(params[:search]).order("created_at DESC")
  end

  private
  def recipe_params
    params.require(:recipe).permit(:title, :process, :details, :main_image, tag_ids: []).merge(user_id: current_user.id)
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def set_recipe_children
    @foodstuff = Foodstuff.new
    @foodstuffs = @recipe.foodstuffs
    @recipephoto = Recipephoto.new
    @recipephotos = @recipe.recipephotos
  end
 
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_comment_form.html.erb
<%= form_for [@recipe, @comment], remote: true do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  <div class="comments_form">
    <div class="comments_forms">
      <%= f.text_area :text, class: "comment_text" %>
    </div>
    <div class="actions_comment">
      <%= f.submit "コメント" %>
    </div>
  </div>
<% end %>

 

app/views/recipes/_foodstuff_form.html.erb
<%= form_for [@recipe, @foodstuff], remote: true do |f| %>
 <%= render 'layouts/error_messages', model: f.object %>
  <div class="foodstuff_form">
    <div class="foodstuff_forms">
      <%= f.text_area :material, placeholder: "     追加する材料" , class: "foodstuff_text" %>
      <%= f.text_area :quantity, placeholder: "    分量", class: "foodstuff_texts" %>
    </div>
    <div class="actions_foodstuff">
      <%= f.submit "追加" %>
    </div>
 </div>
<% end %>

 

app/views/recipes/_form.html.erb
<%= form_with(model: @recipe,local: true) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  <div class="main_contents">
    <div class="image-content">
      <div class="image_preview", id="image-list"></div>
      <% if @recipe.main_image.attached? %>
        <%= image_tag @recipe.main_image, class: "user_image_index" %>
      <% else %>
        <%= image_tag ("photo.jpg") , class: "user_image_index" %> 
      <% end%>
      <%= f.file_field :main_image %> 
    </div>
    <div class="text-content">
      <div class="field">
        <%= f.label :title, "料理名" %><br />
        <%= f.text_field :title , class: :new_form_text %>
      </div>
      <div class="field">
        <%= f.label :process, "紹介文" %><br />
        <%= f.text_area :process, class: :new_form_text %>
      </div>
      <div class="field">
        <%= f.label :details, "何人前" %><br />
        <%= f.text_area :details, class: :new_form_text %>
      </div>
      <span>タグ</span>
      <div class="check_box">
        <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
          <li class="tag-list">
            <%= tag.label do %>
              <%= tag.check_box %>
              <%= tag.text %>
            <% end %>
          </li>
        <% end %>
      </div>
      <div class="actions">
        <%= f.submit "保存する", class: :form__btn  %>
      </div>
    </div>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div class="title_content">
  <div class="title_field">
    <p>紹介文</p>
  </div>
  <div class="title_fields">
    <%= @recipe.process %>
  </div>
</div>
<div class="title_content">
  <div class="title_field">
    <P>分量(何人前)</p>
  </div>
  <div class="title_fields">
    <p><%= @recipe.details %></p>
  </div>
</div>

app/views/recipes/_recipephoto_form.html.erb
<div class="recipe-contents">
  <%= form_for [@recipe, @recipephoto], remote: true do |f| %>
    <div class="recipe-content-show">
      <div class='recipephoto-img'>
        <div class="image_preview", id="image-list"></div>
        <% if @recipephoto.sub_image.attached? %>
          <%= image_tag @recipephoto.sub_image, class: "user_image_index" %>
        <% else %>
          <%= image_tag ("photo.jpg") , class: "user_image_index" %> 
        <% end%>
        <%= f.file_field :sub_image %> 
      </div>
      <p class="recipephoto_texts">
        <%= f.text_area :text, placeholder: "追加する材料" , class: "recipephoto_text" %>
      </p>
      <div class="actions">
        <%= f.submit "追加する" %>
      </div>
    </div> 
  <% end %>
</div>


  

app/views/recipes/edit.html.erb
<div class="form_wrapper">
  <div class="form_inner">
    <div class="title-content">
      <div class="title_recipe">レシピ編集</div>
      <%= render "recipes/form", recipe: @recipe %>
      <div class="actions_edit">
        <%= button_to '削除', recipe_path(@recipe.id), method: :delete, remote: true, data: { confirm: '削除してよろしいですか？' } , class: 'recipe_delete_btn'%>
      </div>
    </div>
    <div class="title_recipe">材料</div>
      <%= render "foodstuffs/foodstuff", foodstuff: @foodstuffs %>
    </div>
  </div>
</div>
<div class="show_links_recipe">
  <div class="title_recipes">作り方</div>
</div>
  <%= render "recipephotos/recipephoto", recipephoto: @recipephotos %>
    </div>
  </div>
</div>

app/views/recipes/edit.index.erb
<div class="main_form">
  <div class="tag-inner">
    <div class="">
      <h2 class="page-heading">新規レシピ投稿</h2>       
      <%= form_with(model: @recipe, url: recipes_path, local: true) do |f| %>
        <div class="field">
          <%= f.label :process, "作り方" %><br />
            <p class="detail__message">
              <%= @recipe.process %>
            </p>
        </div>  
        <div class="main-contents">
          <div class="image-content">
            <%= image_tag @recipe.main_image %>
         </div>
         <div class="from-content">
          <div class="title-content">
            <div class="title-name">
              <p> レシピ</p>
            </div>
          </div>
          <div class="title-content">
            <div class="title-name">
              <p> 料理名 </p>
            </div>
            <div class="valu-name">
              <p><%= @recipe.title %></p>
            </div>
          </div>
          <div class="details-content">
            <div class="title-name">
              <p> 分量(何人前) </p>
            </div>   
            <div class="valu-name">
              <p> <%= @recipe.details %></p>
            </div>
          </div>    
      <% end %>
      <div class="title-content">
        <div class="title-name">
          <p> 材料</p>

        <%= form_with(model: [@recipe, @foodstuff], local: true) do |f| %>
    
          <div class="material-content">
            <div class="field">
              <%= f.label :material, "材料" %><br />
              <%= f.text_field :material %>
            </div>
            <div class="field">
              <%= f.label :quantity, "分量" %><br />
              <%= f.text_field :quantity %>
            </div>

            </div>
              <div class="actions">
                <%= f.submit "保存する", class: :form__btn  %>
              </div>
          </div>
        <% end %>
        </div>
      </div>
       <div class="title-content">
       <% @foodstuffs.each do |foodstuff| %>
         <div class="title-name">
           <p><%= foodstuff.material %></p> 
         </div>
         <div class="valu-name">
           <%= foodstuff.quantity %>
         </div>
        <% end %>
     </div>

    </div>
  </div>
  <div class="tag-contents">
    <div class="prototype__comments">
      <ul class="comments_lists">
          <div class="title-content">
            <div class="title-name">
              <p>作り方</p>
              <div class="prototype__comments">
                <% if user_signed_in?%>
                  <%= form_with(model: [@recipe, @recipephoto], local: true) do |f| %>
                    <%= f.text_field :text %>
                    <%= f.file_field :sub_image %>
                      <div class="actions">
                        <%= f.submit "保存する", class: :form__btn  %>
                      </div>
                  <% end%>
                <% end %> 
                <div class="recipephoto_forms">
                  <% if @recipephotos %>
                    <% @recipephotos.each do |recipephoto| %>
                      <div class="image_content">
                        <div class="recipephoto">
                          <%= image_tag recipephoto.sub_image %>
                          <div class="recipephoto_text">
                            <%= recipephoto.text %>
                          </div>
                        </div>
                      </div>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </ul>
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<div class="main_form">
  <div class="tag-inner">
    <div class="title_recipe">レシピ一覧</div>
    <div class="search">
      <%= form_tag(search_recipes_path,:method => 'get') do %>
        <%= text_field_tag :search, '', placeholder: "キーワード" %>
        <%= submit_tag '検索', :name => nil %>
      <% end %>
    </div>
    <div class="tag-contents">
      <% @recipe.each do |recipe| %>
        <% if recipe.status == "released" %>
          <div class="tag-content-show">
            <div class='tag-images'>
              <%= link_to image_tag(recipe.main_image), recipe_path(recipe.id), method: :get %>
            </div>
            <p class="tags_link">
              <i class="fas fa-utensils"></i>
              <%= link_to recipe.title, recipe_path(recipe.id), method: :get %>
            </p>
            <p class="tags_link">
              <i class="fas fa-user"></i>
              <%= link_to recipe.user.name, user_path(recipe.user.id), method: :get %>
            </p>
          </div> 
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="form_wrapper">
  <div class="title-content">
    <div class="title_recipe">新規レシピ投稿</div>
    <%= render "recipes/form", recipe: @recipe %>
  </div>
</div>

app/views/recipes/recipe_detail.html.erb
<div class="form_wrapper">
  <div class="form_inner">
    <div class="">
      <div class="title-content">
        <div class="title_recipes">新規レシピ投稿</div>
        <%= link_to release_recipe_path(@recipe), method: :patch do %>
          <button class="button_release" >公開にする</button>
        <%end%>
        <div class="main_contents">
          <div class="image-contents">
            <%= image_tag @recipe.main_image %>
          </div>
          <div class="text_content">
            <div class="title_recipe"><p><%= @recipe.title %></p></div>
            <%= render "recipes/recipe", recipe: @recipe %>
            <div class="title_recipe">材料</div>
            <div id="foodstuffs_area">
              <%= render "foodstuffs/create", foodstuffs: @foodstuffs %>
            </div>
            <div class="js-message-errors"></div>
            <%= render "foodstuff_form", recipe: @recipe,foodstuff: @foodstuff %>
          </div>
        </div>
      </div>
      <div class="recipephoto_form">
        <div id="recipephotos_area">
          <%= render "recipephotos/create", recipephotos: @recipephotos %>
        </div>
        <div class="js-message-errors"></div>
        <%= render "recipephoto_form", recipe: @recipe,recipephoto: @recipephoto %>
      </div>
    </div>
  </div>
</div>

app/views/recipes/search.html.erb
<div class="main_form">
  <div class="tag-inner">
    <div class="title_recipe">検索一覧</div>
      <div class="search">
        <%= form_tag(search_recipes_path,:method => 'get') do %>
          <%= text_field_tag :search, '', placeholder: "キーワード" %>
          <%= submit_tag '検索', :name => nil %>
        <% end %>
      </div>
      <div class="tag-contents">
        <% @recipes.each do |recipe| %>
          <% if recipe.status == "released" %>
            <div class="tag-content-show">
              <div class='tag-images'>
                <%= link_to image_tag(recipe.main_image), recipe_path(recipe.id), method: :get %>
              </div>
              <p class="tags_link">
                <i class="fas fa-utensils"></i>
                <%= link_to recipe.title, recipe_path(recipe.id), method: :get %>
              </p>
              <p class="tags_link">
                <i class="fas fa-user"></i>
                <%= link_to recipe.user.name, user_path(recipe.user.id), method: :get %>
              </p>
            </div> 
          <% end %>
        <% end %>
      </div>
      <a><%= link_to "戻る", root_path,  class: :root_btn %></a>
    </div>
  </div>
</div>
 
 

 

app/views/recipes/show.html.erb
<div class="form_wrapper">
  <div class="title-content">
    <div class="button_link">
      <div class="show_link">
        <% if user_signed_in? && current_user.id == @recipe.user_id %>
          <% if @recipe.released? %>
            <%= link_to nonrelease_recipe_path(@recipe), method: :patch do %>
              <button class="button_release" >非公開にする</button>
            <%end%>
          <% else %>
            <%= link_to release_recipe_path(@recipe), method: :patch do %>
              <button class="button_release" >公開にする</button>
            <%end%>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="main_contents">
      <div class="image-contents">
        <%= image_tag @recipe.main_image %>
        <p class="tags_link">
          <i class="fas fa-calendar-alt"></i>
          <%= l @recipe.created_at %>
          <i class="fas fa-user"></i>
          <%= link_to @recipe.user.name, user_path(@recipe.user.id), method: :get %>
          <i class="fas fa-comment"></i>
          <%= @recipe.comments.count%>
        </p>
      </div>
      <div class="text_content">
        <div class="show_links">
          <div class="title_recipes"><%= @recipe.title %></div>
          <div class="show_link">
            <% if user_signed_in? && current_user.id == @recipe.user_id %>
              <%=link_to edit_recipe_path(@recipe.id), method: :get do %>
                <button class="button_show_link" >編集</button>
              <%end%>
            <% end %>
          </div>
        </div>
        <%= render "recipes/recipe", recipe: @recipe %>
        <div class="show_links">
          <div class="title_recipes">材料</div>
          <div class="show_link">
            <% if user_signed_in? && current_user.id == @recipe.user_id %>
              <%=link_to edit_recipe_foodstuff_path(@recipe.id), method: :get do %>
                <button class="button_show_link" >編集</button>
              <%end%>
            <% end %>
          </div>
        </div>
        <%= render "foodstuffs/foodstuff", foodstuff: @foodstuffs %>
      </div>
    </div>
  </div>
  <div class="show_links_recipe">
    <div class="title_recipes">作り方</div>
    <div class="show_link">
      <% if user_signed_in? && current_user.id == @recipe.user_id %>
        <%=link_to edit_recipe_recipephoto_path(@recipe.id), method: :get do %>
          <button class="button_show_link" >編集</button>
        <%end%>
      <% end %>
    </div>
  </div>
  <%= render "recipephotos/recipephoto", recipephoto: @recipephotos %>
  <div class="show_links_recipe">
    <div class="title_recipes">Comment</div>
  </div>
  <div class="comment_content">
    <div id="comments_area">
      <%= render "comments/create", comments: @comments %>
    </div>
    <div class="show_links_recipe">
      <div class="title_recipes">New Comment</div>
    </div>
    <div class="js-message-errors"></div>
      <%= render "comment_form", recipe: @recipe,comment: @comment %>
    </div>
  </div>
</div>
 