config/routes.rb
Rails.application.routes.draw do

  root to: 'tags#index'

  devise_for :admins, skip: :all
  devise_scope :admin do
    
    get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
    post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'
    delete 'admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'    
  end

  namespace :admins do
    get '/' => 'tags#index', as: 'top'
    resources :tags
    resources :recipes do
      resources :foodstuffs
      resources :recipephotos
      collection do
        get 'search'
      end
    end
    resources :users
  end

  devise_for :users, skip: :all
  devise_scope :user do
    get 'users/sign_in' => 'users/sessions#new', as: 'new_user_session'
    post 'users/sign_in' => 'users/sessions#create', as: 'user_session'
    delete 'users/sign_out' => 'users/sessions#destroy', as: 'destroy_user_session'
    get 'users/sign_up' => 'users/registrations#new', as: 'new_user_registration'
    post 'users' => 'users/registrations#create', as: 'user_registration'
    get 'users/password/new' => 'users/passwords#new', as: 'new_user_password'
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users do
    member do
      get 'nonreleases'
    end
  end

  resources :tags 

  resources :recipes do
    resources :foodstuffs
    resources :recipephotos
    resources :comments
    member do
      get 'recipe_detail'
      get 'nonreleases'
      patch 'nonrelease'
      patch 'release'
    end
    collection do
      get 'search'
    end
  end

end

app/models/recipephoto.rb
class Recipephoto < ApplicationRecord
  belongs_to :recipe, optional: true
  has_one_attached :sub_image
  
  validates :text, presence: true
end

app/controllers/admins/recipephotos_controller.rb
class Admins::RecipephotosController < ApplicationController
  before_action :authenticate_admin!
  def create
    @recipe = Recipe.find params[:recipe_id]
    @recipephoto = Recipephoto.new(recipephoto_params)
    if @recipephoto.save
      render :create
    else
      render :errors
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
    @foodstuff = Foodstuff.new
    @foodstuffs = @recipe.foodstuffs
    @recipephoto = Recipephoto.new
    @recipephotos = @recipe.recipephotos.order(created_at: :desc)
  end

  def destroy
    @recipephoto = Recipephoto.find(params[:id]) 
    if @recipephoto.destroy!
      render :create
    end
  end

  private
  def recipephoto_params
    params.require(:recipephoto).permit(:text, :sub_image).merge(recipe_id: params[:recipe_id])
  end

end

app/controllers/recipephotos_controller.rb
class RecipephotosController < ApplicationController
  before_action :authenticate_user!

  def create
    @recipe = Recipe.find params[:recipe_id]
    @recipephoto = Recipephoto.new(recipephoto_params)
    if @recipephoto.save
      render :create
    else
      render :errors 
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
    @foodstuff = Foodstuff.new
    @foodstuffs = @recipe.foodstuffs
    @recipephoto = Recipephoto.new
    @recipephotos = @recipe.recipephotos
  end

  def destroy
    @recipephoto = Recipephoto.find(params[:id]) 
    if @recipephoto.destroy!
      render :create
    end
  end
  
  private
  def recipephoto_params
    params.require(:recipephoto).permit(:text, :sub_image).merge(recipe_id: params[:recipe_id])
  end

end

app/helpers/recipephotos_helper.rb
module RecipephotosHelper
end

app/views/admins/recipephotos/_create.html.erb
   <div class="title_recipe">レシピ画像・テキスト</div>
<div class="recipe-contents">
  <% recipephotos.each do |recipephoto| %>
    <div class="recipe-content-show">
      <div class='recipephoto-image'>
      <% if recipephoto.sub_image.attached? %>
        <div class='recipephoto-images'>
            <%= image_tag recipephoto.sub_image, class: "user_image_index" %>
            </div>
          <% else %>
          <div class='recipephoto-img'>
            <%= image_tag ("photo.jpg") , class: "none_image" %> 
            </div>
          <% end%>
      </div>
      <p class="recipephoto_texts">
        <p><%= recipephoto.text %></p> 
      </p>
      <%= button_to '削除', recipe_recipephoto_path(recipephoto.recipe_id, recipephoto.id), method: :delete, remote: true, data: { confirm: '削除してよろしいですか？' } , class: 'recipephoto_btn'%>
    </div> 
  <% end %>
</div>



 

app/views/admins/recipephotos/_form.html.erb
<%= form_with(model: [recipe, recipephoto], url: recipe_recipephoto_path(@recipe) ) do |f| %>
  <%= f.text_area :content, class: "input-mysize" %>
  <%= f.submit "送信", class: "btn btn-outline-dark comment-submit float-right" %>
<% end %>

app/views/admins/recipephotos/create.js.erb
$("#recipephotos_area").html("<%= j(render 'create', { recipephotos:  @recipephoto.recipe.recipephotos }) %>")
$("textarea").val('')
$("input#recipephoto_sub_image").val('')

app/views/admins/recipephotos/edit.html.erb
<div class="form_wrapper">
  <div class="form_inner">
    <div class="title-content">
      <div class="button_link">
        <div class="show_link">
          <% if user_signed_in? && current_user.id == @recipe.user_id %>
            <% if @recipe.released? %>
              <%= link_to nonrelease_recipe_path(@recipe), method: :patch do %>
                <button class="button_release" >非公開にする</button>
              <%end%>
            <% else %>
              <%= link_to release_recipe_path(@recipe), method: :patch do %>
                <button class="button_release" >公開にする</button>
              <%end%>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="main_contents">
        <div class="image-contents">
          <%= image_tag @recipe.main_image %>
          <p class="tags_link">
            <i class="fas fa-calendar-alt"></i>
            <%= l @recipe.created_at %>
            <i class="fas fa-user"></i>
            <%= link_to @recipe.user.name, user_path(@recipe.user.id), method: :get %>
          </p>
        </div>
        <div class="text_content">
          <div class="title_recipe">レシピ</div>
          <div class="title_content">
            <div class="title_field">
              <P>レシピ名</p>
            </div>
            <div class="title_fields">
              <p><%= @recipe.title %></p>
            </div>
          </div>
        <%= render "recipes/recipe", recipes: @recipes %>
        <div class="title_recipe">材料</div>
         <%= render "foodstuffs/foodstuff", foodstuff: @foodstuffs %>
      </div>
        </div>
      </div>
      <div class="recipephoto_form">
        <div id="recipephotos_area">
          <%= render "recipephotos/create", recipephotos: @recipephotos %>
        </div>
        <div class="js-message-errors"></div>
        <%= render "recipes/recipephoto_form", recipe: @recipe,recipephoto: @recipephoto %>
        <div class="show_link">
            <%= link_to admins_recipe_path(@recipe.id), method: :get do %>
              <button class="button_show_link" >戻る</button>
            <%end%>
        </div>
      </div>
    </div>
  </div>
</div>