config/routes.rb
Rails.application.routes.draw do

  root to: 'tags#index'

  devise_for :admins, skip: :all
  devise_scope :admin do
    
    get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
    post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'
    delete 'admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'    
  end

  namespace :admins do
    get '/' => 'tags#index', as: 'top'
    resources :tags
    resources :recipes do
      resources :foodstuffs
      resources :recipephotos
      collection do
        get 'search'
      end
    end
    resources :users
  end

  devise_for :users, skip: :all
  devise_scope :user do
    get 'users/sign_in' => 'users/sessions#new', as: 'new_user_session'
    post 'users/sign_in' => 'users/sessions#create', as: 'user_session'
    delete 'users/sign_out' => 'users/sessions#destroy', as: 'destroy_user_session'
    get 'users/sign_up' => 'users/registrations#new', as: 'new_user_registration'
    post 'users' => 'users/registrations#create', as: 'user_registration'
    get 'users/password/new' => 'users/passwords#new', as: 'new_user_password'
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users do
    member do
      get 'nonreleases'
    end
  end

  resources :tags 

  resources :recipes do
    resources :foodstuffs
    resources :recipephotos
    resources :comments
    member do
      get 'recipe_detail'
      get 'nonreleases'
      patch 'nonrelease'
      patch 'release'
    end
    collection do
      get 'search'
    end
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :recipe_tag_relations, dependent: :destroy
  has_many :recipes, through: :recipe_tag_relations
  validates :name, :tag_image ,presence: true
  has_one_attached :tag_image
end

app/controllers/admins/tags_controller.rb
class Admins::TagsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_tag, only: [:edit, :update, :destroy]
  def index
  @tags = Tag.all
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    @tag.valid?
    if @tag.save
      redirect_to admins_tags_path
    else
      render :new
    end
  end

  def show
    @tag = Tag.new
  end

  def edit
  end

  def update
    if @tag.update(tag_params)
      redirect_to admins_tags_path
    else
      render :edit
    end
  end

  def destroy
    @tag.destroy
    redirect_to admins_tags_path
  end

  private
  def tag_params
    params.require(:tag).permit(:name, :tag_image)
  end

  def set_tag
    @tag = Tag.find(params[:id])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
    @recipes = @tag.recipes.order("created_at DESC")
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/index.html.erb
<div class="main_form">
  <div class="tag-inner">
    <div class="title_recipe">タグ一覧</div>
    <div class="search">
      <%= form_tag(search_recipes_path,:method => 'get') do %>
        <%= text_field_tag :search, '', placeholder: "キーワード" %>
        <%= submit_tag '検索', :name => nil %>
      <% end %>
    </div>
    <div class="tag-contents">
      <% @tags.each do |tag| %>
        <div class="tag-content-show">
          <div class='tag-images'>
            <%= link_to image_tag(tag.tag_image), tag_path(tag.id), method: :get %>
          </div>
          <p class="tags_link">
            <i class="fas fa-tags"></i>
            <%= link_to tag.name, tag_path(tag.id), method: :get %>
          </p>
        </div> 
      <% end %>
    </div>
  </div>
</div> 
 

app/views/tags/show.html.erb
<div class="main_form">
  <div class="tag-inner">
    <div class="title_recipe"><%= @tag.name %></div>
    <div class="tag-contents">
      <% @recipes.each do |recipe| %>
        <% if recipe.status == "released" %>
          <div class="tag-content-show">
            <div class='tag-images'>
              <%= link_to image_tag(recipe.main_image), recipe_path(recipe.id), method: :get %>
            </div>
            <p class="tags_link">
              <i class="fas fa-utensils"></i>
              <%= link_to recipe.title, recipe_path(recipe.id), method: :get %>
            </p>
            <p class="tags_link">
              <i class="fas fa-user"></i>
              <%= link_to recipe.user.name, user_path(recipe.user.id), method: :get %>
            </p>
          </div> 
        <% end %>
      <% end %>
    </div>
  </div>
</div> 
 